### ISSUE TITLE
run_maintenance with p_analyze := false

### ISSUE THREAD

**Issue by kaxap** [pgpartman/pg_partman#246]
Hi,

So currently in my DB run_maintenance with p_analyze := false can take really long time to complete.
The question is, what happens if I run_maintenance to drop old and create new partitions with p_analyze := false and never run_maintenance with p_analyze := true?

Thanks.

**Comment by keithf4** [comment]
If it is not analyzing, the only thing I can suggest you check is if there are any long running transactions behind held open on any of the partition sets that are having maintenance run on them at the time it seems to be taking longer. A brief lock is required to both add and remove child tables to an inheritance/partition set.

**Comment by keithf4** [comment]
As for the analyze itself, you don't ever have to run it with true. But as I mention in the documentation, it's recommended that you schedule a regular analyze of the partition set's parent to keep the statistics up to date so that constraint exclusion works. This is more important for trigger-based partitioning than native, though.

**Comment by kaxap** [comment]
Thank you for clearing this.
