### ISSUE TITLE
Convert Unlogged table to Logged after move to archive scheme

### ISSUE THREAD

**Issue by evsasha** [pgpartman/pg_partman#250]
Hey. I use `Unlogged `tables to store logs (postgres 9.6).
When partman move this tables to archive schema , they still be `Unlogged`.

I know that if the server crashes, I will lose all the data in all `Unlogged` tables.
But I'm not ready to lose all the data in the archive tables.

This is not clearly described in documentation.

**Comment by keithf4** [comment]
Changing from unlogged to logged (or vice versa) requires an entire table rewrite which could cause a single maintenance run to take hours (or even days) for large tables. So that is not really something suited to the automated partitioning maintenance process, at least as far as this extension is concerned. No other property of a table, besides the schema, is changed in the archive process, so there's no reason to explicitly state that the UNLOGGED property would change either. 

If loss of data is ever a concern, UNLOGGED tables should never be used. As things stand now, if the database ever crashes, you would lose all data in the main partition set.

**Comment by evsasha** [comment]
Thanks, I understood. I just wanted to pay attention to this case.
