### ISSUE TITLE
Create new partitions after modifying optimize_trigger

### ISSUE THREAD

**Issue by priyanshujain** [pgpartman/pg_partman#270]
I tried running create_parent as
```
SELECT partman.create_parent('public.core_rate', 'datetime', 'partman', 'daily');
```
It only created 4 partitions and after that I modified `optimize_trigger` in `part_config` but how can I generate remaining partitions after modifying `optimize_trigger`?

**Comment by keithf4** [comment]
The `optimize_trigger` option only controls which partition names are explicitly named in the conditions inside the trigger function to help increase write performance for that period of time. You only really need to adjust that option if you expect data to be being inserted outside that range of partitions.

What controls how many future partitions are actually made is the `premake` option.

If you're on PG11, I'd recommend going with native partitioning vs trigger-based. Then you don't have to worry about the trigger optimization and performance is a lot better.

**Comment by priyanshujain** [comment]
Thanks a lot @keithf4. Right row we're on PG9.6 and have 300GB of data on single server. We're migrating to a new distributed PG instance with PG11. So on that instance we can apply native partitioning. I already tried it on test server and works good. We're using django and because of that I needed  to apply a small hack as in need to rename old table:

```
ALTER TABLE public.core_rate RENAME TO public.core_rate_bk;

CREATE TABLE public.core_rate (
    id integer NOT NULL,
    ...
    ...
    datetime timestamp with time zone NOT NULL,
)
PARTITION BY RANGE (datetime);

SELECT partman.create_parent('public.core_rate', 'datetime', 'native', 'daily', p_template_table:='public.core_rate_bk');

```

But on our old DB(PG 9.6) I faced problem in migrating data to partitioned tables. After creating partitions on PG9.6 it doesn't automatically move data. I needed to call `partition_data_time` to migrate data to partitions. Is it the expected behaviour or I'm doing something wrong?

**Comment by keithf4** [comment]
Correct it does not move any data at the time of creation. Otherwise it would hold a lock for the entire time the data was moved and you couldn't really do it on a live table, especially large ones.

The `partition_data_time` function will move the data out, but using that will hold a transaction open for the entire duration of a single call. For 9.6 and older, it's better to use the python script that comes with pg_partman: `partition_data.py`. You can commit data in smaller batches with it. For PG11 and later, there are now stored procedures that can do the same.

**Comment by priyanshujain** [comment]
Thank you @keithf4  and apologies for late reply.
