### ISSUE TITLE
Errors in partition_data_proc for native-partitioned table

### ISSUE THREAD

**Issue by nobleread** [pgpartman/pg_partman#273]
I've experienced a problem while calling **partition_data_proc** for time-based partitioned table under partman's control (partitioned natively). Issue was that after adding a single future record, i.e. a record out of retention/premake range, to a (default) table and calling this procedure, I got stuck in a never ending loop in **partition_data_time** function after `ELSIF v_partition_type IN ('time-custom', 'native')` statement - loop's exit condition could never be satisfied and only changing `IF v_start_control > v_max_partition_timestamp THEN` to `IF v_start_control >= v_max_partition_timestamp THEN`, so changing comparison from `>` to `>=`, allowed for whole procedure to exit and do its job. Is this a mistake, that should be fixed in partman's source code?

Second thing I've noticed is that after this record was moved from default table to a proper partition, it seems like run_maintenance does not work properly any longer after part_config.premake param for this table was changed.

Please take a look how I got both errors below.

So I start off with the table configured like this:
```
-[ RECORD 1 ]--------------+--------------------------------------
parent_table               | public.foobar
control                    | datecolumn
partition_type             | native
partition_interval         | 1 day
constraint_cols            |
premake                    | 14
optimize_trigger           | 4
optimize_constraint        | 30
epoch                      | none
inherit_fk                 | t
retention                  | 37 days
retention_schema           |
retention_keep_table       | f
retention_keep_index       | f
infinite_time_partitions   | t
datetime_string            | YYYY_MM_DD
automatic_maintenance      | on
jobmon                     | f
sub_partition_set_full     | f
undo_in_progress           | f
trigger_exception_handling | f
upsert                     |
trigger_return_null        | t
template_table             | partman.template_public_foobar
publications               |
inherit_privileges         | f
constraint_valid           | t
```

Current time is:
```
db=# select now();               
              now                
-------------------------------- 
 09/26/2019 08:29:57.510308 EDT  
(1 row)                     
```     

Adding a 'future' record:
`db=# insert into foobar values (..., '11/27/2019');
`

And confirm record was put into default table
```
db=# select * from foobar_default;
... | datecolumn
...-+-----------
... | 11/27/2019

```
Call partition_data_proc with a proposed quickfix - everything works and new partition is created, record is moved properly. Without quickfix, I'm stuck in a never ending loop
```
db=# \d+ foobar
...
foobar_p2019_10_09 FOR VALUES FROM ('10/09/2019') TO ('10/10/2019'),
foobar_p2019_10_10 FOR VALUES FROM ('10/10/2019') TO ('10/11/2019'),
foobar_p2019_11_27 FOR VALUES FROM ('11/27/2019') TO ('11/28/2019'),
foobar_default DEFAULT                                              

db=# select count(*) from foobar_default;
 count                                            
-------                                           
     0                                            
(1 row)                                           
```
Set new premake. 
`db=# update partman.part_config set premake = 100;
`

After running partman.run_maintenance, new partitions are created only after the previously last partition and there's a gap between previously last one and one-before last partition, although  infinite_time_partitions is set to true - so every partition should exist
```
...
pcsa_bookmark_p2019_10_09 FOR VALUES FROM ('10/09/2019') TO ('10/10/2019'),
pcsa_bookmark_p2019_10_10 FOR VALUES FROM ('10/10/2019') TO ('10/11/2019'),
pcsa_bookmark_p2019_11_27 FOR VALUES FROM ('11/27/2019') TO ('11/28/2019'),
pcsa_bookmark_p2019_11_28 FOR VALUES FROM ('11/28/2019') TO ('11/29/2019'),
...
pcsa_bookmark_p2020_01_04 FOR VALUES FROM ('01/04/2020') TO ('01/05/2020'),
pcsa_bookmark_p2020_01_05 FOR VALUES FROM ('01/05/2020') TO ('01/06/2020'),
pcsa_bookmark_p2020_01_06 FOR VALUES FROM ('01/06/2020') TO ('01/07/2020'),
pcsa_bookmark_default DEFAULT                  

```
In case I change premake to other value and run partman.run_maintenance on a table where no record was moved from default, all required partitions are created, so this error appears only when non-continuous partitions exist, which is a result of e.g. calling procedure partition_data_proc. In the end I think that premake don't need to be changed in order for that error to appear; it's just that run_maintenance does not properly handle discontinuous partition range.

**Comment by keithf4** [comment]
You've definitely identified a bug there with the `partition_data_time` function and the solution as well, so thanks very much for that!

If you'd like to write up a full patch release for this as version 4.2.1, I could merge it in. Can see previous updates for examples of what's included in that.

Otherwise, I can include this fix with credit for you in the CHANGELOG with my next release that I'm going to do for fixing tablespace inheritance with PG12 (https://github.com/pgpartman/pg_partman/issues/274). Don't have an ETA on that but shouldn't be too long.

**Comment by keithf4** [comment]
As for the missing gap in the child tables that is because maintenance always bases the next child table to be created either on the maximum control column value or the latest child table created in sequence. Since data got inserted far ahead of the typical premake, all future maintenance is based on that, leaving you with that gap. The best way to avoid that for now is to ensure your premake is high enough to account for the expected time range of incoming data. There's no real penalty for setting it higher outside of current issues with partitions sets having very large numbers of children (1000+). But even many of those issues are fixed in the upcoming 12 release!

I've tried gap filling during maintenance before and it's quite tricky to do in an efficient manner that can be done during normal maintenance runs. I think a better solution would be some other function or functions that could be used to do that gap filling and just be run when needed. I'll make an issue for that feature and also mark it as one that I'll accept contributions for in case you or anyone else wants to work on it. Not sure when I'll have time for that in the near future.

**Comment by nobleread** [comment]
I have opened a pull request with full patch release for this change as version 4.2.1. Hope everything is done properly, and you can just simply merge it.
As to filling gap in partitions - if I can find some time, I will surely take a look at it.

**Comment by keithf4** [comment]
Merged this in and just had to fix one minor thing in the update file. Since it's changing an existing function, it has to be CREATE OR REPLACE there.

Thanks again!
