### ISSUE TITLE
Run partitioning as non-superuser

### ISSUE THREAD

**Issue by hedgss** [pgpartman/pg_partman#285]
Hi,

I need to run partitioning as non-superusers.

1. I executed the following as a non-superuser to create schema, tables and add the extension.
```
CREATE SCHEMA partman;
CREATE EXTENSION pg_partman SCHEMA partman;
```
The following tables were created with owner postgres:
```
my_db=> \dt partman.*
                  List of relations
 Schema  |          Name          | Type  |  Owner
---------+------------------------+-------+----------
 partman | custom_time_partitions | table | postgres
 partman | part_config            | table | postgres
 partman | part_config_sub        | table | postgres
(3 rows)
```
2.  If I run SELECT `partman.create_parent(...)` it fails due to lack of permission.
I granted permission. The next command executed as a superuser
```
# \c my_db
# \conninfo
You are connected to database "my_db" as user "postgres" via socket in "/var/run/postgresql" at port "5432".
# GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA partman TO my_user;
```
3. Now I can create parent and it works.

**Questions:**
-  As far as I understand, each database that requires partitions needs to create own schema where all configuration will be stored. (Step 1). Is it correct?
- To be able to create parent and manage settings I have to add permissions for the user (Step 2). Is it possible to provide an opportunity to create partitions and manage the partitions for all non-superuser users? I mean that non-superuser can manage partitions in the databases and schemas that it has access.

Each user should be able to create and manage own partitions without additional actions as a superuser. Is it possible?

**Comment by hedgss** [comment]
I created a simple bash script that adds all the required things.
Pre-requirements:
- install pg_partman
- install pg_cron
- update   pg_hba. Add line "host    all all 127.0.0.1/32 trust"
If somebody has better solution please let me know.
The script:
```
#!/usr/bin/env bash
USER=$1
DB=$2
PARTITION_SCHEDULE=${3:-"*/4 * * * *"}
RUN_MAINTENANCE="CALL partman.run_maintenance_proc(0, true, false, true)"
script_name=`basename "$0"`

set -e
help() {
cat << EOF

${script_name} - initialize partman for user, grant him permissions and schedule maintenance process.

  ${script_name} <user> <database> <schedule>
    user      - Postgres user
    database  - postgres database for the user
    schedule  - cron schedule how often run partman.run_maintenance_proc procedure. Default value: '*/4 * * * *'
EOF
}

[[ -z ${USER} ]] && echo "ERROR: User is not defined" && help && exit 128
[[ -z ${DB} ]] && echo "ERROR: Database is not defined" && help && exit 128
create_partman_extension() {
  echo "Create partman extension for user ${USER} in db ${DB}"
  psql -U ${USER} ${DB} << EOF
CREATE SCHEMA IF NOT EXISTS  partman;
CREATE EXTENSION IF NOT EXISTS  pg_partman SCHEMA partman;
EOF
}

grant_privileges() {
  echo "Grant permissions in schema partman to user ${USER}"
  psql -U postgres ${DB} << EOF
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA partman TO ${USER};
EOF
}

schedule_partitioning() {
  echo "Schedule partman.run_maintenance_proc for the user ${USER}"
  psql -U postgres << EOF
  INSERT INTO cron.job (schedule, command, nodename, nodeport, database, username)
  VALUES ('${PARTITION_SCHEDULE}', '${RUN_MAINTENANCE}', 'localhost', 5432, '${DB}', '${USER}');
  GRANT USAGE ON SCHEMA cron TO ${USER};
EOF

}
create_partman_extension
grant_privileges
schedule_partitioning
set +e
```

**Comment by keithf4** [comment]
Yes, each database manages its own partitioning configuration. All extensions are installed per-database.

The top level README.md file contains the permissions that are required to run pg_partman as a non-super user. A copy of some example commands is below. By default the EXECUTE privileges should exist, but some people may revoke those by default, so I included them explicitly. You'll also want to grant ALL on any schemas where those roles will be creating tables.

It does require additional GRANTS on a per-database basis to be able to do so, as you've done here. There's no way I can really automate that within pg_partman itself because I don't know what roles will exist and don't want to grant permissions that may not be wanted by default. Your script is a great way to handle it for your situation, tho.

```
CREATE ROLE partman WITH LOGIN;
GRANT ALL ON SCHEMA partman TO partman;
GRANT ALL ON ALL TABLES IN SCHEMA partman TO partman;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA partman TO partman;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA partman TO partman;  -- PG11+ only
GRANT ALL ON SCHEMA my_partition_schema TO partman;
```

**Comment by hedgss** [comment]
@keithf4 
My configuration is based on the top-level README.md file.
But it was not clear for me which user should I use to execute the commands.
e.g. the next command failed if I execute it  as a non-privileged user
```
# GRANT ALL ON ALL TABLES IN SCHEMA partman TO partman;
ERROR:  permission denied for table custom_time_partitions
```
Also, it is not convenient to switch users to execute all required commands to grant all required permissions.
I wrote the script that solves the issue.
Perhaps it can be useful for someone else.
Thank you!

**Comment by keithf4** [comment]
At some point a role with the proper privileges has to do the GRANT to another. Initially that will likely be a superuser. If you actually change the ownership of the pg_partman objects to a non-superuser, you may then be able to use a non-superuser to do the grants. However, there are still some parts of managing pg_partman that at least require the objects being owned by a superuser (if `inherit_privileges` is true) due to the catalog access that is required.
