### ISSUE TITLE
Disabling autovacuum when using native partitioning

### ISSUE THREAD

**Issue by bschofield** [pgpartman/pg_partman#292]
I'm using postgres native partitioning, with pg_partman for automated partition creation and deletion. It works well and I like it -- thank you for creating it, and thank you for continuing to maintain it.

Because the tables which I am partitioning are basically write-only, I want to disable autovacuum on new partitions as they are created. I note in the changelog for pg_partman that it says:-

```
    -- Unable to turn autovacuum off/on reliably in PROCEDURE as was previously done with python scripts. If autovac is an issue when (un)partitioning large tables, recommend manually disabling it.
```

...and I see the corresponding commented-out SQL in the repo code.

My question is: given that PROCEDUREs do not work reliably here, what is the best way to automatically disable autovacuum on new partitions as they are created? At the moment, I'm using pg_cron to run a check every hour, and if there are new partitions with autovac enabled, I disable it. Is this the best thing to do, or am I missing a simpler option?

**Comment by keithf4** [comment]
That autovacuum option is in the `partition_data.py` and `undo_partition.py` python scripts that are still installed for PG10 and older with pg_partman. It was used for when data was being mass migrated either into a child tables or undoing partitioning. It has never been an option for normal partition maintenance.

When you say your new partitions are "write only", do you mean insert only? If so, you should be fine since inserts are not considered when deciding to trigger vacuum a table. Only updates/deletes are considered for when autovacuum should run. Some consider this is actually a long standing issue with insert-only tables since autovacuum won't run normally. 

In either case, autovacuum will still run on these tables eventually when `autovacuum_freeze_max_age` is reached on those tables. And if your tables are getting updates/deletes, you should not be disabling autovacuum on them. 

I may consider adding some more fine-grained autovacuum controls at a later time, specifically the autovacuum scale/threshold values on the parent. I'm curious to see if those may already be inherited with native partitioning. If not, I'd actually consider that a bug and something that should be fixed in core.

**Comment by bschofield** [comment]
Thanks for the response. Yes, my partitioned tables are indeed insert-only. I hadn't appreciated that autovacuum won't try to run unless there are updates or delete on a table. That being the case, I don't need to disable autovacuum at all... so I won't! Also a useful tip on `autovacuum_freeze_max_age`, I will experiment with some tuning there.

The specific autovacuum code that I was talking about is the commented-out code at lines 64, 114, 127 of https://github.com/pgpartman/pg_partman/blob/5f6fa69751d47b385a2e067ce781eb3c41282ca7/sql/procedures/partition_data_proc.sql. I had assumed this SQL was used as part of normal partition maintenance, but after actually reading the comments in the CHANGELOG I see exactly what you mean.
