### ISSUE TITLE
Question: Clean up partitioned data from parent table?

### ISSUE THREAD

**Issue by ChillarAnand** [pgpartman/pg_partman#306]
On an existing large table, after partman creates partitions by date, should partman delete data from the parent table?

```
drop database sandbox;

create database sandbox;


\c sandbox;

create table author (
       id serial primary key not null,
       created_at timestamp with time zone not null,
       updated_at timestamp with time zone not null,
       name varchar(32)
)
;

CREATE SCHEMA partman;
CREATE EXTENSION pg_partman SCHEMA partman;

insert into author values (20,
'2020-01-01 21:49:22.742914+05:30',
'2020-01-01 21:49:22.742914+05:30',
'author2');

insert into author (created_at, updated_at, name) values (now(), now(), 'author4');

SELECT partman.create_parent('public.author', 'created_at', 'partman', 'daily');

select * from author order by created_at desc;
```

After that when maintenance task is run, it is creating appropriate partitions with data but it is not deleting data from the parent table.

**Comment by keithf4** [comment]
No, `create_parent` does not move any data to avoid locking for long periods of time during setup.

The `partition_data_*` functions can be used to move the data out of the parent/default into the proper children. If you're moving a lot of data, I'd recommend looking at using the `partition_data.py` python script instead.

I recall from your other issue that you're on PG10? I would highly recommend looking into upgrading to a more recent major version and switch to using native partitioning instead of using the old trigger-based partitioning. Assuming that's what you're using since you're talking about data in the parent.

**Comment by ChillarAnand** [comment]
Thanks, @keithf4. I was using PG10 for testing but I am using 9.6 in production and can't use native partitioning as of now. 

Will check `partition_data.py` script.
