### ISSUE TITLE
How to uninstall pg_partman?

### ISSUE THREAD

**Issue by dtseiler** [pgpartman/pg_partman#321]
Good afternoon Keith,

We have one DB where pg_partman was set up in staging and UAT before they decided to abandon that project altogether. But they want to keep the parent tables.

So I just want to know what is the best way to remove pg_partman but leave the data as it is for now. Do I just drop the partman extension and then drop the partman schema and its objects and then remove the bgw from `shared_preload_libraries`?

**Comment by keithf4** [comment]
Is this trigger-based partitioning or native partitioning? 

If trigger-based, that's more difficult because the trigger functions use functions from pg_partman, so you'd have to rewrite all of those to no longer do so. Otherwise, you'd only be able to read the tables, but never write to them without possibly throwing errors.

If not trigger-based, and using native, then I believe your steps should be fine to follow. Uninstalling the extension should drop all of the relevant objects so all you'll be left with is the tables and the schema that the extension was installed in.

Honestly, tho, part of me would recommend trying to unpartition the data before removing pg_partman. Just to leave things in a simpler state if possible, moving all the data back to the parent table.

**Comment by dtseiler** [comment]
This is using trigger-based inheritance-style old-school partitioning on PG10. Could we just drop the trigger from the parent table and then drop the trigger function?

There's actually no data in any of the child tables. So I would use the `undo_partition.py` script. Does that also drop the trigger?

**Comment by keithf4** [comment]
Yes, the unpartitioning process built into pg_partman also drops the triggers. So that's another good reason to go through it that way. Been so long since I've done trigger-based partitioning, I'd forgotten it manages all that too. 

The python script is basically calling this function internally https://github.com/pgpartman/pg_partman/blob/master/sql/functions/undo_partition.sql

If there's no data in any children, then that basically means there's no data (unless it had already been purposely going to the parent for some reason). The python script is mostly for managing things in batches when moving large amounts of data. Since there's no data, could just go with the undo_partition() function directly.

**Comment by dtseiler** [comment]
One UAT table has data in the parent table for some reason, which is why I phrased it that way. But the one child table it has is empty. Will that complicate things?

**Comment by dtseiler** [comment]
Looks like it all ran fine, thanks again!

For the record I did this:

1. `select partman.undo_partition('public.foo');
2. `drop table <foo child table(s)>;' (I could have set `p_keep_table` to `false` in step 1)
3. `drop extension pg_partman;`
4. `drop schema partman;`
