### ISSUE TITLE
Complete file pg_partman--2.3.4.sql

### ISSUE THREAD

**Issue by tiago-cruz-movile** [pgpartman/pg_partman#322]
Hello,

Do you have the complete file `pg_partman--2.3.4.sql`?
I can't find this file, even in the tag `v2.3.4`

The file `pg_partman--2.3.4--2.4.0.sql` don't work in `default_version` from pg_partman.control

**Comment by keithf4** [comment]
You must run `make` to generate the pg_partman--x.x.x.sql files for installation.

The pg_partman--x.x.x--x.x.x.sql files are only for doing updates to an existing installation.

Also, 2.3.4 is extremely old and there have been many, many new features and bug fixes since then. I would highly recommend installing the latest version (4.4.0).
