### ISSUE TITLE
Question: How to convert a regular table to partitioned table using native range partition?

### ISSUE THREAD

**Issue by arrowwood49** [pgpartman/pg_partman#325]
I'm planning to use Postgres 12 native range partition and use pg_partman to automate partition creation and removal.

What are the steps to convert a regular table to a partitioned table and migrate data?

Thanks

**Comment by keithf4** [comment]
This is something I've long been wanting to make a howto document on, however the time has just been lacking. I'll try and see if I can get something going now that there's a specific ask in the issues. 

You cannot directly turn a basic table into a partitioned table. You must migrate the data to a newly created partition table. 

If you can take an outage long enough to move the data from one table to another, it's simply a matter of making a new parent table, running `create_parent()` on it, then using the `partition_data_proc()` procedure to move the data from one table to the other. You can either swap the table names before or after the migration.

If you need to do this online, it's a bit trickier. You must still create a new parent, but you can make the old table the `default` partition of the new parent. You can do that, along with some table name swapping, all within a single transaction so it's invisible to the user. Now you have all your data in a single child table that you can again, use the `partition_data_proc()` procedure to then move the data out of the default partition. Note that with native, you must still move all the data that would go into a single child table in one transaction, so if there's a lot, you could still have some heavy row contention during the migration.

Just noticed that the docs still say the `partition_data_proc()` cannot work on the `default` partition. That's not true and was added in 4.1.0.

**Comment by arrowwood49** [comment]
Thanks @keithf4 for the suggestions.

Can you elaborate on using a single transaction that you mentioned?
>  Note that with native, you must still move all the data that would go into a single child table in one transaction, 

We can't take a long outage so I'm thinking to do it in two phases. First set up the old table as the default partition when all client applications are stopped. Setting the default partition with the old table should be a quick operation. All applications can be restarted after that so they can continue to read and write to the partitioned table. 
In the second phase, I can run partition_data_proc() to move data from the default partition to specific partitions. 
This worked but I had to pass the future timestamp value for 'p_start_partition' param to create_parent() function since it was failing with "ERROR:  partition constraint is violated by some row”. 

The partition_data_proc() procedure created all old partitions while moving the data out of the default partition. However, an exclusive lock is required on the parent table when multiple old partitions are created during data migration. Is there any trick to avoid the lock contention from partition creation during the data migration phase?

**Comment by keithf4** [comment]
I do have a document on migrating an existing non-native, trigger-based partition set to native here - https://github.com/pgpartman/pg_partman/blob/master/doc/migrate_to_native.md You can see an example of running some commands in a single transaction. This blog post on removing a lot of old data also gives an example of using transactional DDL - https://www.keithf4.com/removing-old-data/

Two phase approach sounds good. And good catch with the `p_start_partition`. I believe @dtseiler  was running into this same issue as well trying to do the same thing. You may want to reference his issue - https://github.com/pgpartman/pg_partman/issues/324#issuecomment-694378671

Only thing I can think of to try and reduce locking is to just do a batch size of 1 child table at a time to avoid possibly longer locks of needing to make multiple child tables at once. As new major versions are releasing, the lock levels that are required when managing partitions are going down. But that takes time. Not sure if 13 fixed that yet or not. Pretty sure removing child tables has had its lock levels reduced in 12. 

The bigger problem is likely what @dtseiler ran into in that you must move the data in chunks the size of an entire single child partition. If that turns out to be a problem, maybe try migrating to a trigger-based solution first that can do it in smaller chunks, then migrate that to native using the above doc? But then you have to take the possibly very noticeable performance hit to your writes.

My advice to people lately is that, if it's at all possibly to schedule an outage to do a migration to native partitioning, then try and see if that can happen. Otherwise you're often having to do a lot of workarounds to try and accommodate people still using your data when trying to move it around between tables. The one longer outage may be less of a hassle in the long run vs possibly having many brief outages over time.

**Comment by arrowwood49** [comment]
Thanks @keithf4 for sharing the references. Those are very helpful.

I was able to simplify the data migration further for my use-case by using the phased approach:

phase 1 runs during a short outage window to setup DB schema. During this phase, all partitions required for old data will be pre-created using `create_parent()` to avoid locking contention later.
All queries are currently through DB views so views can be changed to combine data from both old tables and new partitioned tables. The service that writes to the table will be upgraded with a new code to start writing to the new partitioned table. So there is no backward compatibility needed for writes and using DB views makes the query transparent to table changes.

phase 2:  Data migration will be started during this phase when all applications and services are running. I will use the source table approach instead of the default partition to migrate data using `partition_data_proc()` procedure. The source table approach is more flexible since data can be migrated in smaller chunks.

**Comment by keithf4** [comment]
That's a very interesting approach. Would be curious to hear how it goes and maybe share some additional details if you wouldn't mind. Always interested in finding better ways to handle the migration process since it's gotten a bit more challenging with native.

**Comment by arrowwood49** [comment]
Sure @keithf4, I'll start working on this soon in my project and I will update here with an example.

**Comment by dtseiler** [comment]
Good point about having all the setup DDL in a transaction. I'll be sure to keep that in mind for my migrations. Also fair point about going with the inheritance/trigger based method to initially partition the data in smaller intervals and then migrate to native.

I'm considering a half lazy approach where I take a brief downtime to do the intiial partitioning and default partition swap. But then rather than call `partition_data_proc()`, I could just keep calling the `DELETE` we have now to delete data older than X days until the default partition is empty (in X days), or just stop calling it for X days and then truncate the default partition. The second idea would obviously require more storage to hold the data until I can truncate and vacuum that default partition afterward.

**Comment by dtseiler** [comment]
> If that turns out to be a problem, maybe try migrating to a trigger-based solution first that can do it in smaller chunks, then migrate that to native using the above doc? But then you have to take the possibly very noticeable performance hit to your writes.

I'm looking at now having to do a different migration and considering first using trigger-based to control the batch size and then migrating to native at a later date. I'm curious what "very noticeable performance hit" to writes you're referring to here. A performance hit from using trigger-based partitioning? Or during the migration itself?

**Comment by keithf4** [comment]
Trigger-based partitioning. Depending on what your write rate was before, you could see a fairly noticeable difference

**Comment by dtseiler** [comment]
OK good to know, I wasn't aware of that possibility but I suppose that makes sense if every insert now has to process a trigger.

**Comment by keithf4** [comment]
Created a howto doc for converting a normal table to a natively partitioned table

https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman_howto_native.md

**Comment by darksheik** [comment]
The idea of simply making your old table the default partition of the new is ingenious.  I thought I was in for an extended downtime copying tens of gigs of data over!
