### ISSUE TITLE
Q: [native] Should I have non-unique indexes in a template table or on the parent table?

### ISSUE THREAD

**Issue by dtseiler** [pgpartman/pg_partman#328]
Playing with PG12 and native partitioning. I was looking at some non-unique indexes in my sample case and wondering if you'd recommend having them on the template table (if used for partition-specific PK/UK constraints) or if they'd be better served being added to the parent table?

Is there a performance benefit to either one?

**Comment by keithf4** [comment]
Whether a non-unique index is done on the parent or the template table is based on the version of PG you're running, no other reason. See the table in the documentation for feature support per-version:  https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#child-table-property-inheritance

**Comment by dtseiler** [comment]
But on PG12 I *could* still use the template table for non-unique indexes, which I was doing until I thought about this last week. My question was more for which is more appropriate but I take it that using the parent table is preferred in PG12 for everything but PK/UK constraints and unlogged tables.

**Comment by keithf4** [comment]
I've actually been removing template support in pg_partman where it's not needed anymore. Can't recall if I actually removed non-unique index support, but if not, I will at some point in the future. Template is really only there to help with native short-comings so if they're fixed in native, it would be preferred to use the native method.

**Comment by dtseiler** [comment]
OK sounds good, thanks.
