### ISSUE TITLE
Failure when attaching the default partition

### ISSUE THREAD

**Issue by bilby91** [pgpartman/pg_partman#349]
Hello,

I'm following this guide https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman_howto_native.md#online-partitioning to move data into a partitioned table.

The DDL of the original table looks like this:

```
CREATE TABLE gfv2.visits (
 id                    bigint not null default nextval('new_visits_id_seq') ,
 location_id           integer                                              ,
 asset_id              integer                                              ,
 tag_id                integer                                              ,
 start_tag_reading_id  bigint                                               ,
 end_tag_reading_id    bigint                                               ,
 created_at            timestamp without time zone not null                 ,
 updated_at            timestamp without time zone                          ,
 constraint new_visits_pkey PRIMARY KEY (id)
);
```

The partitioned table looks like this:

```
CREATE TABLE gfv2.visits_part (
 id                    bigint                      not null ,
 location_id           integer                              ,
 asset_id              integer                              ,
 tag_id                integer                              ,
 start_tag_reading_id  bigint                               ,
 end_tag_reading_id    bigint                               ,
 created_at            timestamp without time zone not null ,
 updated_at            timestamp without time zone          ,
 constraint visits_pkey PRIMARY KEY (id, created_at)
)
PARTITION BY RANGE (created_at);
```

I'm trying to figure out why Postgres is complaining about constraints being violated. I'm able to follow all the steps up to that attachment of the default partition.

```
geoforce=# ALTER TABLE gfv2.visits ATTACH PARTITION gfv2.visits_default DEFAULT;
ERROR:  partition constraint is violated by some row
```

I even pre-created all the different partitions thinking that could be the problem but it doesn't seem to be the case.

**Comment by keithf4** [comment]
Do you have any data in your default partition that also matches data in an already existing child table? If so, you will have to move that data out of the default before you can attach it as one.

**Comment by keithf4** [comment]
The other issue may be this key part of that document you listed
`The tricky part here is that we cannot yet have any child tables in the partition set that match data that currently exists in the original table. This is because we're going to be adding the old table as the DEFAULT table to our new partition table. If the DEFAULT table contains any data that matches a current child table's constraints, PostgreSQL will not allow that table to be added. So, with the below create_parent() call, we're going to start the partition set well ahead of the data we inserted. In your case you will have to look at your current data set and pick a value well ahead of the current working set of data that may get inserted before you are able to run the table name swap process below. We're also setting the premake value to a low value to avoid having to rename too many child tables later. We'll increase premake back up to the default later (or you can set it to whatever you require).`

**Comment by bilby91** [comment]
Oh. I overlooked that. Will try something out and report back. Thanks!

**Comment by bilby91** [comment]
That did the trick. 

Thanks!
