### ISSUE TITLE
Config Query/Feature Request

### ISSUE THREAD

**Issue by jake2184** [pgpartman/pg_partman#351]
I'm hoping to move a partition to a different tablespace with run_maintenance(), rather than dropping it. I've seen in some pg_partman docs that you support moving tables to a separate schema instead of dropping them - do you also support altering tablespace?

For example, I have 60 days of data partitioned by day. I only have a limited amount of fast SSD, but a lot of remote storage. Can I have a retention policy where 1-7 days are in the default tablespace with the parent table, 8-60 days are kept on a slower tablespace, and 60+ days are dropped?

I presume if the answer to the above is "no" I can run a script myself to alter the table space of child tables without interfering with pg_partman?

**Comment by keithf4** [comment]
Moving schemas is a very simple catalog change, so can be handled by normal maintenance runs without much issue. Also that move takes the table completely out of the partition set as well. partman does not support a single partition set with children in different schemas. Also, currently pg_partman handles the tablespace by making it match either the parent or template table so it wouldn't easily support multiple tablespaces in a single partition set.

Moving tablespaces in most cases would likely require either a rewrite of the tables or at least moving that data across storage mediums since the main usage of tablespaces in PostgreSQL is splitting objects across multiple storage backends as you're doing here. So that wouldn't fit well with the normal maintenance of pg_partman which generally should be rather quick. So your last idea of using a script to manage this yourself would likely be the best course of action. I don't think partman is checking that all tablespaces match at all times, it's just setting the tablespace during new child tables creation.

**Comment by jake2184** [comment]
ok, thanks for the answer, I'll attempt to do the move myself and hope it doesn't take too long.
