### ISSUE TITLE
Question in Automatic Partition Creation

### ISSUE THREAD

**Issue by Manisankar95** [pgpartman/pg_partman#385]
Hi All,

I have question in the working of pg_partman. Currently pg_partman only create a set of new partition only if there are any data in existing partitioned table (Using native partitioning, PG13). However what if i am not going to get any data for the last 4 (premake value) partitioned table then all of a sudden i am going to get data for future partition range, In this case data will be loaded into default partition and once this happened we need to do some manual effort to move the data to a different table and then move it back to the original table after creating the partition.

Is there any future enhancement in pipeline to create new partition in any scenario even if we do not have data in existing partitioned table ?

Also i am looking for the code where partman is checking if any existing partitioned table is having any records or not. I don't see we have any triggers which does this work!!! Just curious to know how and where this logic is implemented to check for records in existing partitioned table and then it creates a new set of partitioned table.

**Comment by keithf4** [comment]
My initial suggestion is to plan your premake/partition interval to account for your expected time interval, including where expected gaps may exist. There's nothing wrong with increasing the premake value above 4 to higher values like 10, 20 or more. The initial setup will create many child tables at once, but from then on, only fewer additional child tables get created at a time as long as the maintenance interval is running often enough and data insertion resumes again. As soon as new data starts getting inserted again after a gap, as long as the premake was high enough, that child table should exist and the next maintenance run will create as many child tables as needed to meet the premake requirement.

The other option is to set the `infinite_time_partitions` option in the `part_config` table. This causes maintenance to continue making child tables for time-based partition sets based on CURRENT_TIMESTAMP vs the data that exists in the child table. This means there should never be gaps in the child tables, no matter the gap in data insertion. But this does also mean that even if data insertion stops all-together, child tables still keep getting created forever (ie infinitely). This is not the default because integer/id based partitioning can only make new child tables based on the data, so I kept the default behavior consistent between the two.

For native partitioning, the bounds checking for existing data is all internal to PostgreSQL. As you saw, there are no user visible triggers with native partitioning.

**Comment by keithf4** [comment]
Also, if you do find data going into the default, the `partition_data_*` functions/procedure handles moving the data around via temp tables to allow creation of the necessary child table. So if you do run into that issue, it shouldn't be much of a hassle from the maintenance point of view. May be more of an issue if the users are trying to use that data, though, since it will require a lock on those rows to move them around.

**Comment by Manisankar95** [comment]
Thank you very much for your quick response. I will follow the suggested approach. Seems like i need to go-through the documentation properly 😊. Some how missed this infinite_time_partitions setting. I used below command to test this out.

CREATE TABLE test.part_test3 (col1 serial, col2 text, col3 timestamptz NOT NULL DEFAULT now()) PARTITION BY RANGE (col3);
SELECT partman.create_parent('test.part_test3', 'col3', 'native', 'quarter-hour', p_premake => 5);
update partman.part_config set infinite_time_partitions = 't' where parent_table = 'test.part_test3';

The background worker was set to run every 5 minutes.

**Comment by keithf4** [comment]
As long as the background worker runs at least twice within your smallest partition interval, that should be fine. If you find the messages in the log getting excessive.
