### ISSUE TITLE
How to configure retention policy for daily partitions?

### ISSUE THREAD

**Issue by kartikdc** [pgpartman/pg_partman#394]
In the part_config table, what should I set `retention` to if I want to keep partitions for (let's say) the last 30 days? The reason I ask is that from reading the docs, it isn't too clear to me:

> For time-based partitioning, the interval value will set that any partitions containing only data older than that will be dropped.

Can I set it to something like `retention='30 days'`?

**Comment by keithf4** [comment]
Yes, that is correct. The retention column is a text column since it could contain an interval for either time or integer-based partitioning. In the case of time, this should be a literal `interval` data type value, which `30 days` is. This means that any child table that contains _only_ data that is _older_ than 30 days will be dropped. So if the child table has any data at all that isn't older than 30 days, it will not be dropped yet.

**Comment by kartikdc** [comment]
@keithf4 Thanks. Do you think it would be better to use Discussions for questions like this?

**Comment by keithf4** [comment]
General questions like this are probably better on the Discussions.
