### ISSUE TITLE
Clarification of maintenance process

### ISSUE THREAD

**Issue by jarrettprosser** [pgpartman/pg_partman#398]
Howdy,

I'm trying to determine if pg_partman is the right partitioning solution for our application and would like to get some clarification on the general behaviour and the maintenance process. 

We have an application which processes timeseries data. It can process current data, but for new customers we will often load historical data. At the moment, when we create a new partitioned table, it creates the default of 9 partitions. For example, if the table is partitioned daily and we create it today, we would have partitions spanning from 26/09/2021 - 05/11/2021.

When we are loading historical data which may be weeks or months in the past, there is no partition which matches the time key for the data, and so it is being inserted into the default partition. Is that the correct behaviour? Others on my team expected that partman would create a new partition on insert, but I can't see evidence of that behaviour. 

From here, I had thought the background worker, through `run_maintenance`, would move data out of the default partition, creating new partitions as needed, but it appears that the maintenance process fails if there isn't already a partition for the data.
```
postgres=> call partman.run_maintenance_proc();
ERROR:  updated partition constraint for default partition would be violated by some row
CONTEXT: SQL statement "ALTER TABLE ada.connection_point_interval ATTACH PARTITION ada.connection_point_interval_p2021_10_26 FOR VALUES FROM ('2021-10-26 00:00:00+00') TO ('2021-10-27 00:00:00+00')"
```
I have found that to resolve this, I need to run `partition_data_proc` on each affected table, then I can `run_maintenance_proc`. Is that the correct approach?

If so, is there some way I can automate this process so that I won't need to manually tend to the database? And should we be using a different process (pre-creating historic partitions, for instance)? It seems like we're double handling a lot of the data if it needs to get moved regularly. 

Thanks very much for the extension and all your work on it.

**Comment by keithf4** [comment]
> Howdy,
> 
> I'm trying to determine if pg_partman is the right partitioning solution for our application and would like to get some clarification on the general behaviour and the maintenance process.
> 
> We have an application which processes timeseries data. It can process current data, but for new customers we will often load historical data. At the moment, when we create a new partitioned table, it creates the default of 9 partitions. For example, if the table is partitioned daily and we create it today, we would have partitions spanning from 26/09/2021 - 05/11/2021.
> 
> When we are loading historical data which may be weeks or months in the past, there is no partition which matches the time key for the data, and so it is being inserted into the default partition. Is that the correct behaviour? Others on my team expected that partman would create a new partition on insert, but I can't see evidence of that behaviour.

Inserting data that does not have a proper child table does place that data into the default partition if one exists. Creation of a default partition is something pg_partman does for you automatically to help avoid possible data loss unintentionally. It is possible to create a partition set without a default which would then cause an error if the proper child table doesn't exist.

Other partition management systems do attempt to make a child table as needed, but for PostgreSQL this can cause contention since DDL is transactional. One transaction would attempt to make the needed child table then another could come in requesting the same then possibly cause a block on all subsequent transactions until the first completes. Therefore pg_partman goes with the option to premake child tables before they're needed.

> 
> From here, I had thought the background worker, through `run_maintenance`, would move data out of the default partition, creating new partitions as needed, but it appears that the maintenance process fails if there isn't already a partition for the data.
> 
> ```
> postgres=> call partman.run_maintenance_proc();
> ERROR:  updated partition constraint for default partition would be violated by some row
> CONTEXT: SQL statement "ALTER TABLE ada.connection_point_interval ATTACH PARTITION ada.connection_point_interval_p2021_10_26 FOR VALUES FROM ('2021-10-26 00:00:00+00') TO ('2021-10-27 00:00:00+00')"
> ```
> 
> I have found that to resolve this, I need to run `partition_data_proc` on each affected table, then I can `run_maintenance_proc`. Is that the correct approach?
> 
> If so, is there some way I can automate this process so that I won't need to manually tend to the database? And should we be using a different process (pre-creating historic partitions, for instance)? It seems like we're double handling a lot of the data if it needs to get moved regularly.
> 
> Thanks very much for the extension and all your work on it.

pg_partman's normal maintenance process does not move data out of the default. The addition of new child tables and dropping of old ones can cause some locking on the partition sets, so maintenance is made to run as quickly as possible.

If data exists in the default, and a new child table that would contain that data tries to be attached, an error will be thrown. This is a core feature of PostgreSQL and not something pg_partman is causing. The default child table basically has an anti-constraint on it that is the opposite of all existing child tables. So when you try and add a new child table, PostgreSQL sees that data already exists in the default so won't let you add a child table that has the same constraint. If there's no existing matching data in the default, PG automatically redoes the default table's constraint.

The `partition_data_proc()` procedure handles moving data out of the default for you by first moving it to a temp table, creating the child table, then moving it back. So yes, this could create a lot of additional writes if this would be something that's happening regularly. 

I would suggest creating a partition set starting with a child table as far back as you expect to have data being inserted. When you run `create_parent()` you can give it a desired starting point. You could temporarily set the premake high enough to make enough child tables to be caught up to "now()" then set it back to your normally expected time window of data.

If you cannot predict how far back you will be inserting past data, then it's going to be tricky to handle no matter which partitioning solution you use. If you don't want to lose the data, it's going to have to go to a default of some sort to later be sorted out. And you don't want to just leave that in the default since, every time you add a child table, PostgreSQL has to check the default to see if data exists there. If there are billions of rows in the default, it can take a very long time to scan that even with an index, and cause significant delays during maintenance.

Hopefully that helps you decide whether pg_partman can work for you. Let me know if you have any other questions.

**Comment by jarrettprosser** [comment]
Thanks for the info! That's very helpful in confirming what I thought was going on under the hood, and your reasoning makes a lot of sense. We'll implement some changes to our processes to better accomodate this behaviour.
