### ISSUE TITLE
Multiple partitioned tables interfere during maintenance

### ISSUE THREAD

**Issue by nivbend** [pgpartman/pg_partman#421]
This isn't an issue per se, more of a question of clarification about proper usage of `pg_partman`.

We're using `pg_partman` to partition multiple tables, some across multiple schemas if that's relevant (PG11+, native partitioning, all of which are partitioned by time). We have `pg_cron` running `run_maintenance_proc` routinely and `infinite_time_partitions` set to `TRUE` on all tables.

The issue arises usually when we add or modify a partitioned table, missing setting `infinite_time_partitions` to `TRUE` or otherwise misconfiguring things (totally our bad, not `pg_partman`'s fault). The next time `run_maintenance_proc` runs it fails on the new/modified table, but then it won't create new partitions for the rest of the tables.

I'm wondering if there's a best practice we're missing here?
Would it be better to add a cronjob with `run_maintenance(p_parent_table  => ...)` for each individual table to avoid such interference?

**Comment by keithf4** [comment]
If problems with maintenance on one table are a concern with interfering with other tables, then yes, doing maintenance calls individually per table is the best way to go. Just make sure to then set `automatic_maintenance` to false in the configuration table so that if a maintenance call with no parameter is called, it doesn't run on those. 

These sorts of situations is why automatic maintenance was made optional.

**Comment by nivbend** [comment]
Okay, thanks for the clarification!
