### ISSUE TITLE
partman running as non super user creates partition using postgres user

### ISSUE THREAD

**Issue by saxenakshitiz** [pgpartman/pg_partman#485]
I have setup partman to run as a non-super user(say kshitiz). When I run `SELECT partman.create_parent (...)` , the child partition tables are created with owner as my user `kshitiz`. I have further configured cron job to perform partition maintenance by calling `CALL partman.run_maintenance_proc()`. This continues to run fine for some time, and continue to create new child partition tables with owner as my user `kshitiz`. However at some point of time, it does create child partition table with owner as user `postgres`. Once that happens, the partition maintenance  stops working as my user `kshitiz` does not have access to child partition table with owner as `postgres`. I am unable to find root cause for this issue.
Really appreciate any help to debug/fix this issue.

**Comment by keithf4** [comment]
I'll have to look more closely when I have some more time, but the only thing that comes to mind is possibly another cronjob on the system running as the postgres user. Or maybe do you have the background worker set to run as well? The BGW runs as the `postgres` user by default, so if that happens to run sometime between when your cronjob does and it makes a new table, it would be owned by that user.

**Comment by saxenakshitiz** [comment]
The maintenance cron job is running as user `kshitiz` for sure. No other maintenance job is running. How can I check for this `background worker`?

**Comment by keithf4** [comment]
This would be configured in the postgresql.conf file as a `shared_preload_library` entry as well as possibly having some additional variables that start with `pg_partman_bgw`. See the INSTALLATION section of the README for more info on the BGW - https://github.com/pgpartman/pg_partman#installation

So far the only way I'm seeing this happen on the more recent version of pg_partman is if maintenance is run by two different users for the same table and, at the time that maintenance is called by the secondary user, a child table is created. The fact that it is happening sometime after the initial setup points to this as well as it may indicate that maybe someone had previously set up pg_partman on this system and either had a cronjob already in place or the background worker set up. That other job would kick in and run maintenance as needed, possibly replacing the maintenance that your cronjob would do.

One experiment you could do would be to set the `automatic_maintenance` column in the `part_config` table to false for your partition table. That will stop any other general calls to `run_maintenance()` (including the BGW) from creating any new tables on your partition set. In your cronjob, you would then need to call `run_maintenance('myschema.mytable')` instead of `run_maintenance_proc()` to run the maintenance process on your one, specific partition set (the procedure does not take a single table argument).

https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#tables

Also, what version of pg_partman are you running?

**Comment by saxenakshitiz** [comment]
@keithf4 Thanks for all your inputs. I believe the issue is with bgw running as `postgres` user. I will make that change.
