### ISSUE TITLE
Offline partitioning is moving 0 rows at final step despite identical source and destination tables

### ISSUE THREAD

**Issue by cathanod** [pgpartman/pg_partman#486]
I've been following the official documentation for pg_partman, specifically partitoning an existing table using offline partitioning (https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman_howto_native.md).

The reason for this change is we wanted to move from ID based list partitioning to monthly range partitioning on a new timestamptz column.

My source and destination table are essentially identical. The only change I have made is the partition column has changed from an ID (using list partitioning) to a newly created timestamptz column (using range partitioning), however this new column exists on both source and destination tables now.

My issue is running 
``` 
CALL partman.partition_data_proc(p_parent_table := 'public.partitioned_table', p_interval := '1000', p_batch := 200, p_source_table := 'public.nonpartitioned_table');
```

produces the following output:
```
Total rows moved: 0
Ensure to VACUUM ANALYZE the parent (and source table if used) after partitioning data
```

Despite the source table having hundreds of thousands of rows to move.

Is there any way to enable verbose debugging or getting some indication of why this proc is not moving rows?

Edit:

Testing a straight insert/select moved the data fine, but this seems like a bad way to do things.

```
insert into public.partitioned_table select * from public.nonpartitioned_table;
```

Also noticed in doing this that the create_parent function created my partition bounds incorrectly, the setup I used was:

`
SELECT partman.create_parent(
p_parent_table => 'public.partitioned_table', 
p_control => 'created_at', 
p_type => 'native', 
p_interval => '30 days',
p_start_partition := '2022-06-19 00:00:00.000 +0100'::text,
p_premake => 6);
`

Which created the following partitions:
![image](https://user-images.githubusercontent.com/51191789/191546101-3bc5ecfb-f56b-4123-b2fc-04feb9e5b1eb.png)

As you can see, partition p2022_08 starts at 2022-08-30 and ends at 2022-09-29 rather than starting at 2022-07-31.

**Comment by keithf4** [comment]
Will have to look more closely at the first part of your issue, but one thing I see off the bat is you are explicitly setting the interval to `30 days` instead of `1 month`. So it's doing exactly that.
```
keith@keith=# select '2022-08-30'::timestamptz + '30 days'::interval;
        ?column?        
------------------------
 2022-09-29 00:00:00-04
(1 row)

Time: 20.628 ms
keith@keith=# select '2022-08-30'::timestamptz + '1 month'::interval;
        ?column?        
------------------------
 2022-09-30 00:00:00-04
(1 row)

Time: 0.422 ms
```

**Comment by cathanod** [comment]
Oh yes the upper bound isn't the part that was concerning me. I'll try to be more clear:

If you notice the partitions p2022_07 it starts at 07-01 and ends at 07-31, the next partition at p2022_08 then starts at 08-30 for some reason, which is different from the behaviour of all of the other upper and lower bounds.

For example if we look at the upper bound for p2022_10 it is 11-28, then the next partition's (p2022_11) lower bound is 11-28 as expected. For some reason there is a whole 30 days being skipped.

**Comment by keithf4** [comment]
Yeah, I think something may be getting conflated with it trying to use monthly partition table names vs the boundaries being a static 30 days. I'm not sure pg_partman is going to work right as it is right now because of that. 

I have some plans in the upcoming 5.x refactor to change the partition child names to something a little more standard that should work better for more strict interval values like this. In the mean time, I would suggest setting your interval to `1 month`.

**Comment by keithf4** [comment]
Actually, the `p_date_trunc_interval` parameter to create_parent() may help solve this. See the doc entry for `create_parent()` here https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#creation-functions

You might have to set this value to `day` so that the partitions are named on a daily basis vs a monthly basis.

**Comment by keithf4** [comment]
So I think the issue is that the underlying `partition_data_time/id()` functions are doing a `SELECT [...] FROM ONLY ...`. Since the parent table is empty in a partition set, it's grabbing nothing.

https://github.com/pgpartman/pg_partman/blob/master/sql/functions/partition_data_time.sql#L163

I hadn't planned on using the partition_data functions for moving data from one partition set to another at the time these were written. There might be some other reasons for this left over from trigger-based partitioning as well. I'll write this down as something to investigate for the 5.x refactor that's dropping trigger-based partitioning.

So for now, you will have to do that INSERT INTO ... SELECT * method for now. If you'd rather not do that in one giant transaction, which is why I'm assuming you were trying to use the procedure, you can prepare some statements with specific WHERE conditions on the SELECT to do the conversion in similar batches.

**Comment by cathanod** [comment]
I think you're right with the partition naming. I'll have a play around with that and let you know if it solves things.

Thanks for the help on this, I'm happy enough to use the INSERT ... SELECT commit workaround for now too. I'll comment my steps to resolve this once I get it working then close this out in case anyone else has this same issue in the future.

Thanks again keith!
