### ISSUE TITLE
Make default partition optional (was: Avoiding "_default" partition)

### ISSUE THREAD

**Issue by ultimoamore** [pgpartman/pg_partman#489]
When inserting data for which there's no partition I'd rather have errors than have a "_default" partition.
Is there any way to avoid creating the "_default" partition when creating partitions?

**Comment by keithf4** [comment]
Apologies for the delay in response. The default partition is always created by default by pg_partman, but you are free to drop it after the partition set it created. I've been debating about making that optional in the `create_parent()` function since it's easy to just drop it vs potentially make a partition set that can lose data by default.

**Comment by keithf4** [comment]
I will be making this an option to `create_parent()` in 5.x

**Comment by keithf4** [comment]
Version 5.0.0 has been released with this feature. Let me know if it's working ok for you.

**Comment by ultimoamore** [comment]
I won't be able to test it (gone with custom drop table at the very beginning of master table creation in my code) but thank you for the change!
