### ISSUE TITLE
Future dated data inserted into default table, breaks run_maintenance

### ISSUE THREAD

**Issue by amasses** [pgpartman/pg_partman#493]
Given a table as follows, partitioned by date (month):
```
Name: transactions
Columns:
  id bigint
  date timestamp
  description varchar(255)
```
And the current date is 2022-11-30

If we have the following partitions setup:

* transactions_p2022_11
* transactions_p2022_10
* etc

If a record is inserted that is future dated (say 2023-05-01) the data will (correctly) be placed into the `transactions_default` table. However when `run_maintenance()` is called for the table it throws an error because Postgresql sees a conflict between the data in the `transactions_default` table versus the new partition table(s) which will be created.

In this case, what is the best way to handle it? Should we be telling partman to pre-make tables for +12 months (or whatever the upper bounds of the future dating might be), or is there something we are missing here which will handle this automatically (i.e. should something be calling the `partition_data_time` functions etc)?

**Comment by keithf4** [comment]
Pre-making partitions for your expected data window is the best practice. If that is unknown, or literally anything, then you'll just have to plan for the following solutions to fix things.

If the data is valid, the way to fix this would be to use the `partition_data*` functions/procedure to move the data out of the default to the proper child. If this is far into the future beyond the most recently created child by normal maintenance, you'll then have a gap in the child tables. That can be fixed with `partition_gap_fill()`.

If the data is invalid, simply deleting the data from the default is the best way.

**Comment by amasses** [comment]
Thanks @keithf4.

Is there any way to automate these tasks either as part of the `run_maintenance` function, or some other way?

**Comment by keithf4** [comment]
I do not have partitioning of data out of the default as a part of normal maintenance at this time. If there was a large batch of data inserted, it could potentially cause more problems than help trying to automate out millions+ of bad rows as part of regular maintenance.

Rather than try to automate that, I'd simply recommend setting up monitoring of your default tables with the `check_default()` function and have it alert you when data goes into the default. Then take the appropriate action from there. Maybe if the row count is low enough, you could automate the partitioning/gap fill process. But if it's above a threshold, require manual investigation/intervention to avoid a lot of bad data or expensive data migration operations.

**Comment by keithf4** [comment]
Closing this issue for now. Please feel free to reopen if you have any further questions
