### ISSUE TITLE
Question : Migrating existing table

### ISSUE THREAD

**Issue by anthares** [pgpartman/pg_partman#527]
Hello,

We are planning to use pg_partman on an existing table.
This table must remain online during this process, so I read the documentation for that use case.

I understand the usage of existing table a default partition.
But I wonder if it might be possible to attach existing table as an history partition, and let it live until retention kicks in.
This will ease the process by skipping data movement.

My understanding is pg_partman relies on table names to determine which table needs to be dropped.
If I use monthly partitioning, how am I supposed to name this history table ? As of first month of data ? or as of last month ?
Or am I going the wrong way and should I drop this history table manually next year ?

Lastly, our table is referenced by foreign keys. And how postgres/pg_partman will behave when applying retention (dropping old partitions) is not clear to me.
I'm expecting the detach to fail, but I've not found any clue in postgres doc (yet).

Thanks!
Best regards,

Nicolas

**Comment by keithf4** [comment]
Leaving data in the default can be problematic for several reasons

- This may not be relevant to you, but you cannot add new child tables that match any data in the default. This is a limitation of PG itself, not pg_partman. 
- But this part is relevant. Because of the above requirement, every row that exists in the default must be compared to the constraint of any new child table when it is added. If you have a lot of data, this can greatly impact the speed of maintenance and possibly cause locking/contention issues.

So that last point is generally why it is discouraged to have any data in the default for an extensive period of time. If there's not a lot of data in your case, it may be ok to let it expire off by itself, but you'll have to test and see.

The currently released version of partman does rely on the name of the child table to help determine retention. However, it also expects that the data contained in any child table is within the interval size. It looks at the child table name as the minimum value then the maximum value as being `min + partition interval`. So even if you rename it to match the same naming pattern, automated retention will not work and may even throw errors. 

Version 5.x currently in development actually looks at the native partition boundaries, so this would likely work with this version. However I do not have a solid ETA for it's release at this time. I'm shooting for this summer.

Foreign Keys TO the partition set can be particularly tricky. Especially if you want to use retention. The child tables cannot be dropped if the table referencing it still has data that it needs. The drop cascade option does not work as expected either because it can completely remove the FK from the whole set vs just the child table. You will have to be 100% sure that all referencing data is removed first before automatic retention will work without throwing an error.

Hope that helps!

**Comment by anthares** [comment]
Hello,

Thank you for answering so quickly.

Regarding "historical" partition, this summer is fine for us, so we'll wait for 5.x.
I'll try to run some tests when it's in beta/RC.

Regarding foreign key, I understand the `drop table <partition> cascade;` is problematic.
I ran a few tests, `on delete cascade` clause on foreign key is not triggered in this case.
The only think working running `run_maintenance` manually on referencing table, then running it on referenced table.
Which is, as you said, ensuring nothing references data in partition that are about to be dropped.

Once again, thank you for your time, things are more clear to me now.
Best regards,

Nicolas

**Comment by keithf4** [comment]
Closing issue for now. Please feel free to reopen if you have any other questions on this topic.

**Comment by smcgivern** [comment]
@keithf4 thanks for your work on this project, it's really helpful.

We're using partman 5.X and looking to convert an existing table to be partitioned. We would like to create the partition set and attach the current table as the first partition, rather than the default partition (which is problematic for the reasons mentioned above and in the howto).

Should this work in partman 5.X? I figure you'll have a better idea now that's actually been released 🙂

**Comment by keithf4** [comment]
Yes, it should work in 5.x since it now uses the actual boundaries, not the child table names. The latest version also has an option to not add a default table when running `create_parent()` so you can add your other table after things are initially set up.

**Comment by smcgivern** [comment]
Great, thank you!
