### ISSUE TITLE
Question: how long should it take to run partman.run_maintenance_proc() and how frequently should it be run?

### ISSUE THREAD

**Issue by spolan9** [pgpartman/pg_partman#549]
Currently have a Postgres database set up on GCP and I set up pg_partman ~1.5 months ago. Unfortunately, at the time I did not realize that the background worker for automated maintenance is not available for GCP hosted Postgres instances.

I was experiencing some performance issues with my parent table in addition to realizing additional partitions were not being automatically created as needed.

My table is set up to be partitioned in weekly increments, with ~2gb of data per child table. The parent table is currently ~20gb in size and growing so nothing too crazy.

In an attempt to catch up the tables maintenance, I have tried to run `partman.run_maintenance_proc()` manually, but it has been running for ~19 hours and counting. I am wondering if this is normal to catch up on ~1.5 months of non-maintenance? If not, what else can be done…do I need to rebuild the table from scratch?

And finally, now that I know I have to schedule the maintenance myself, how frequently should it be run and what is a _‘normal’_ time for it to take to run if run at the proper intervals.

I’ll admit I am quite new to this so any help or guidance here would be much appreciated!

Thanks,
Shane

**Comment by keithf4** [comment]
The only thing run_maintenance is doing is creating new tables, and if you have retention set up, removing old ones. It should generally not take that long. The most common cause of this process being held up is long running/open transactions on the partition set. Check for those first. If you're looking to move unpartitioned data out to child tables, you'll want to be looking at the `partition_data_proc()` procedure.

Can you confirm whether you are doing trigger-based partitioning or native, declarative partitioning? This could possibly matter for some edge cases when running maintenance. I ask because you mention data being in the parent table and that only happens with trigger-based partitioning.

To answer the timing question, you want maintenance to run often enough to keep up with your smallest partition interval. So say you have a combination of daily, weekly and yearly partition sets. You'd want to run it at least once, maybe twice a day to keep up with the smallest daily set. I say maybe twice because sometimes, depending on the timing of the run, it could miss that it needs a new partition for that time. Generally another run evenly spaced out over that smallest interval is enough to catch most timing edge cases.

**Comment by spolan9** [comment]
Thank you for the quick response!

There shouldn't be any long running/open transactions. Is there an easy way to check for this to confirm?

Some data got added into the default partition child table, so I was attempting to run the maintenance first, and then `partition_data_proc()`... I just have yet to have the maintenance finish.

The partitioning was set up as native with a weekly interval, so I think i just misspoke when referencing data in the parent table: `SELECT partman.create_parent('table name', 'date, 'native', 'weekly');`

**Comment by keithf4** [comment]
With native partitioning, if there is a lot of data in the default, this can cause the maintenance process to take longer. This is because when you add a new child table, it has to validate that new child's constraints don't match any data in the default. However, it shouldn't be anywhere near that long if it's only 20GB of data. User that originally reported had billions of rows in the default and it was making maintenance take about 15-25 minutes.

``` select *, now() - xact_start as runtime from pg_stat_activity where state <> 'idle' and backend_type = 'client backend' order by xact_start;```

That should show you all running client connections along with their transaction runtime starting with longest first.

**Comment by spolan9** [comment]
So it seems a few transactions actually got hung up from a failure. I was able to cancel the transactions and successfully run `partman.run_maintenance_proc()`.

Thank you so much for the help!
