### ISSUE TITLE
FK Errors on partition_data_proc version 4.7.3

### ISSUE THREAD

**Issue by Asafb26** [pgpartman/pg_partman#633]
I followed your guide for table offline migrations to support FK migration, but once I invoke the `partition_data_proc` for the legacy table I get foreign key constraint error.
Is FK enabled migration supported on partman 4.7.3? am I missing some configuration?

Im using RDS aurora which is currently supported partman v4.7.3 only, and something is quite odd there (for example I had to provide the `p_type => 'native'` param for the `create_parent` procedure, which has no defaults there)

```sql
ALTER TABLE public.schema_transaction RENAME TO schema_transaction_old;

CREATE TABLE public.schema_transaction (
    timestamp timestamp with time zone NOT NULL,
    id numeric(46,30)
)
PARTITION BY RANGE (timestamp);

CREATE TABLE public.schema_transaction_template (LIKE public.schema_transaction);

ALTER TABLE public.schema_transaction_template ADD PRIMARY KEY (id);

SELECT partman.create_parent(
    p_parent_table => 'public.schema_transaction'
    , p_control => 'timestamp'
    , p_interval => '1 month'
    , p_type => 'native'
    , p_template_table => 'public.schema_transaction_template'
);

CALL partman.partition_data_proc(
    p_parent_table => 'public.schema_transaction'
    , p_interval => '1000'
    , p_source_table =>'public.schema_transaction_old'
);
```

result:
```sql
NOTICE:  Batch: 1, Rows moved: 3
ERROR:  update or delete on table "schema_transaction_old" violates foreign key constraint "schema_subtransaction_tx_id_c3421e20_fk_schema_transaction_id" on table "schema_subtransaction"
DETAIL:  Key (id)=(0.000000163504281852329360640000) is still referenced from table "schema_subtransaction".
CONTEXT:  PL/pgSQL function partman.partition_data_proc(text,text,integer,integer,text,text,integer,integer,boolean,text[]) line 110 at COMMIT
```

**Comment by keithf4** [comment]
The current documentation for migration is for version 5.x. The syntax for many functions has changed since 4.x, so your best bet is to grab one of the older releases and read the documentation from that for better clarity.

https://github.com/pgpartman/pg_partman/releases/tag/v4.7.4

However, re-reading it again myself, it does state that the foreign keys have to be recreated from scratch. That means you'll have to remove ALL foreign keys TO the original table before you partition it. Then do the migration to a partitioned table to move all the data to the relavant child tables. THEN you can recreate the foreign keys to that newly partitioned table.

If that's what you did and it's not working, I'm going to need a fully reproducible example to see where it's failing for you because recreating them from scratch has worked for me so far. Seeing an FK error when you're running the `partiton_data_proc()` procedure shows me that the FK may be in place before the new partition set is fully set up. Your example doesn't have to be your original tables with a ton of data. Just the schema of the tables involved, a little bit of data to make an FK reference and then the steps you ran when setting up the partition set that produce the error.

**Comment by Asafb26** [comment]
Got it, I misunderstood that the migration process handled the FK updata for me, which is not the case as you explained:

```

IMPORTANT NOTE REGARDING FOREIGN KEYS

Taking the partitioned table offline is the only method that realistically works when you have foreign keys TO the table being partitioned. Since a brand new table must be created no matter what, the foreign key must also be recreated, so an outage involving all tables that are part of the FK relationship must be taken. A shorter outage may be possible with the online method below, but if you have to take an outage, this offline method is easier.

```

I probably got misled by the fact that it seemed (at least to me) too implicit that we should remove the FK constraint before and re-create it after, which led me to think partition_data_proc would handle it, since I assumed there should have been steps in this guide to remove and recreate the FK.

Thank you for clarifying!
