### ISSUE TITLE
future partition possibility

### ISSUE THREAD

**Issue by seadba** [pgpartman/pg_partman#682]
hello we use partman for a daily-partitioned table - we maintain 6 months of partitions and run the maintenance proc daily to add/prune partitions
we have had issues in the past where future records appear ,  if valid, we then run partition_data_time and partition_gap_fill -  this works very well 
my question is, if data arrives that is 7 months in the future, and we run the above processes, will the next maintenance_proc will prune all existing partitions? thats a doomsday scenario

i assume so , so we would need to safely delete those rows from default, correct?  thanks - no rush this more of a curiousity but i would like to be ready for it

**Comment by keithf4** [comment]
As of version 5.0, all data in the default partition is ignored when creating future partitions and evaluating retention rules. So as long as you never partition that data out of the default to create a real child table, then it will never consider anything except the existing child tables when removing older partitions.

So, I would highly recommend validating the data in the default before you run the partition_data_time() functions. I would never recommend automating moving data out of the default if it is ever found. If you are frequently getting data out of bounds of the existing children, you can adjust your premake value to cover the expected window of data.

Even saying all that, I'm still not actually 100% sure it would actually prune all the existing children. Partman will never delete ALL the children. It always keeps at least one since it needs a baseline to work from so it knows what future partitions to create.

**Comment by keithf4** [comment]
I would highly recommend running a scenario in a test environment and see what happens.

**Comment by seadba** [comment]
thanks we are testing that now - we are currently running 5.1  -  in the past we have received data for 2026  - its hard to adjust for that - thanks for the fast response
